# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

scholar:
  style: springer-basic-author-date
  locale: en

  sort_by: year
  order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}} {% if link %}  <a href=\"{{ link }}\">Link</a> {% endif %}"

  repository: papers
  bibtex_skip_fields: 
      - url
      - abstract
      - month_numeric

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
