theme: jekyll-theme-tactile
title:       "Nanne"
email:       nanne@uvt.nl
author:      Nanne van Noord
url:         "http://nanne.github.io"
description: "Page with very little info about me"
show_downloads: "false"

# Social icons
github_username: nanne
scholar_username: wFDJzDkAAAAJ
twitter_username: nannevn

# Build settings
markdown:     kramdown
permalink:    pretty
sass:
  compressed: true
