theme: plainwhite
title:       "Nanne"
email:       nannevannoord@gmail.com
author:      Nanne van Noord
url:         "http://nanne.github.io"
description: "Nanne's website"
show_excerpts: true

plainwhite:
  name: Nanne van Noord
  tagline: Assistant Professor of Visual Culture and Multimedia
  date_format: "%b %-d, %Y"
  sitemap: true 
  search: false 
  dark_mode: true
  portfolio_image: "assets/me.png" 
  html_lang: "en" 
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    twitter: nannevn
    github:  nanne
    scholar: wFDJzDkAAAAJ
  navigation: 
    - title: About
      url: "/about"
    - title: Contact
      url: "mailto:n.j.e.vannoord@uva.nl"

# Build settings
remote_theme: samarsault/plainwhite-jekyll
markdown:     kramdown
permalink:    pretty
sass:
        sass_dir: _sass
