# Site settings
title:       "Nanne"
email:       nanne@uvt.nl
author:      Nanne van Noord
url:         "http://nanne.github.io"
description: "Everything about me in one spot!"

# Social icons
show_social_icons: true
github_username: nanne
scholar_username: wFDJzDkAAAAJ
twitter_username: nannevn

# Build settings
markdown:     kramdown
permalink:    pretty
sass:
  compressed: true
